### ISSUE TITLE
Running chef-client on new node overwrites it completely

### ISSUE THREAD

**Issue by dimtruck** [mmi-cookbooks/chef-client#6]
1. I staged `/etc/chef/client.rb` to run chef-zero (local mode true)
2. I ran api node
3. https://github.com/mmi-cookbooks/chef-client/blob/master/recipes/config.rb#L40-L47 overwrote my client.rb and stops me from rerunning chef unless I restage client.rb

**Comment by dimtruck** [comment]
Not chef-client issue but racker/chef instead (https://github.com/racker/chef/issues/4007)

**Comment by mburns** [comment]
fixed in #7
